### ISSUE TITLE
plugin ignores custom definitions when places in an external file

### ISSUE THREAD

**Issue by tomeraz** [neverendingqs/serverless-dotenv-plugin#61] opened 2020-07-19 07:12 UTC
My serverless.yml references an external file:
```
custom: ${file(../../serverless.common.yml):custom}
```
Placing settings inside serverless.common.yml:
```
custom:
  dotenv:
    path: ../../.env
```
serverless.dotenv-plugin ignores these settings.
When debugging plugin code, row 13 leaves this.config undefined:
```
    this.config =
      this.serverless.service.custom && this.serverless.service.custom['dotenv']
```
because ```this.serverless.service.custom``` equals: ```"${file(../../serverless.common.yml):custom}"```

**Comment by neverendingqs** [comment] 2021-02-06 22:58
This looks like a duplicate of https://github.com/neverendingqs/serverless-dotenv-plugin/issues/52, and I would like to keep the conversation. Please reopen this issue if it is not.

Thanks!

**Closed as completed by neverendingqs** 2021-02-06 22:58 UTC
Labels: bug, duplicate
